# -*- coding: utf-8 -*-
"""book.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N3Q-lGpWRA0ZnhFplVjcQFYJ8RXQPnyJ
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans

df = pd.read_csv("books.csv")


#NLP - TF IDF Vectorization


tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(df["combined_features"])


#Cosine Similarity

similarity = cosine_similarity(tfidf_matrix)

#Recommendation Function

def recommend(book):


    if book not in df["Book Name"].values:
        return "Book not found"


    index = df[df["Book Name"] == book].index[0]


    scores = list(enumerate(similarity[index]))


    scores = sorted(scores, key=lambda x: x[1], reverse=True)


    books = []

    for i in scores[1:6]:
        books.append(df.iloc[i[0]]["Book Name"])

    return books

#Clustering using KMeans

k = 10

kmeans = KMeans(n_clusters=k, random_state=42)

df["cluster"] = kmeans.fit_predict(tfidf_matrix)


#Cluster Recommendation


def cluster_recommend(book):

    if book not in df["Book Name"].values:
        return "Book not found"
    cluster_id = df[df["Book Name"] == book]["cluster"].values[0]
    books = df[df["cluster"] == cluster_id]["Book Name"].tolist()
    books.remove(book)

    return books[:5]


#Model Evaluation

def evaluate_precision(book):

    recommended_books = recommend(book)

    if isinstance(recommended_books, str):
        return recommended_books

    input_genre = df[df["Book Name"] == book]["Genres_text"].values[0]

    if input_genre == "" or input_genre == "unknown":
        return "Genre not available for evaluation"

    recommended_genres = df[
        df["Book Name"].isin(recommended_books)
    ]["Genres_text"]

    relevant = 0

    for g in recommended_genres:

        if any(word in str(g) for word in input_genre.split()):
            relevant += 1

    precision = relevant / len(recommended_books)

    return precision



cluster_recommend("Legend")

['The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers',
 'Men Are from Mars, Women Are from Venus: The Classic Guide to Understanding the Opposite Sex',
 'Hit Refresh',
 'A Suitable Boy (Dramatised)',
 'Take Control of Your Life: How to Silence Fear and Win the Mental Game']



evaluate_precision("Thinking, Fast and Slow")
1.0
